f1 <- factor(sample(LETTERS,size=6,replace=TRUE))
f2 <- factor(sample(LETTERS,size=6,replace=TRUE))
print("ORIGINAL FACTORS:")
print(f1)
print(f2)
f=factor(c(levels(f1)[f1],levels(f2)[f2]))
print("AFTER CONCATENATE FACTOR BECOMES:")
print(f)
print("SORT IN DESCENDING ORDER:")
print(sort(f,decreasing = TRUE))