print("FIRST 10 LETTERS IN LOWER CASE:")
t=head(letters,10)
print(t)
print("LAST 10 LETTERS IN UPPER CASE:")
t=tail(LETTERS,10)
print(t)
print("LETTERS BETWEEN 22ND TO 24ND LETTERS IN UPPER CASE:")
e=tail(LETTERS[22:24])
print(e)